language: emacs-lisp
sudo: required
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml
install:
  # For opam instructions see: http://opam.ocaml.org/doc/Install.html
  - wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh
  - yes | sh ./opam_installer.sh /usr/local/bin $OCAML_VERSION
env:
  - OCAML_VERSION=4.04.1 EVM_EMACS=emacs-24.3-travis
  - OCAML_VERSION=4.04.1 EVM_EMACS=emacs-24.4-travis
  - OCAML_VERSION=4.04.1 EVM_EMACS=emacs-24.5-travis
  - OCAML_VERSION=4.04.1 EVM_EMACS=emacs-25.1-travis
  - OCAML_VERSION=4.04.1 EVM_EMACS=emacs-git-snapshot-travis
script:
  - opam install merlin.2.5.5 -y
  - ./run-travis-ci.sh

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis
